// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyFiles(arg1:main.CopyRequest):Promise<main.CopySummary>;

export function ListFiles(arg1:main.ListOptions):Promise<Array<main.FileInfo>>;

export function PickDirectory(arg1:string):Promise<string>;
